extends RefCounted

# Generated by Scripts/Tools/bake_u13_castle_fracture.py.
# Gravity + polygon contacts + a four-wall container, baked offline.
# Runtime only interpolates these shared shapes. Consumers must not mutate.
static var _poses: Array = [
	[
		PackedVector2Array([Vector2(0.00000000, 0.00000000), Vector2(0.51000000, 0.00000000), Vector2(0.40000000, 0.39000000)]),
		PackedVector2Array([Vector2(0.00000000, 0.00000000), Vector2(0.40000000, 0.39000000), Vector2(0.00000000, 0.30000000)]),
		PackedVector2Array([Vector2(0.51000000, 0.00000000), Vector2(1.00000000, 0.00000000), Vector2(1.00000000, 0.27000000)]),
		PackedVector2Array([Vector2(0.51000000, 0.00000000), Vector2(1.00000000, 0.27000000), Vector2(0.40000000, 0.39000000)]),
		PackedVector2Array([Vector2(0.00000000, 0.30000000), Vector2(0.40000000, 0.39000000), Vector2(0.61000000, 0.61000000)]),
		PackedVector2Array([Vector2(0.00000000, 0.30000000), Vector2(0.61000000, 0.61000000), Vector2(0.00000000, 0.68000000)]),
		PackedVector2Array([Vector2(0.40000000, 0.39000000), Vector2(1.00000000, 0.27000000), Vector2(1.00000000, 0.74000000)]),
		PackedVector2Array([Vector2(0.40000000, 0.39000000), Vector2(1.00000000, 0.74000000), Vector2(0.61000000, 0.61000000)]),
		PackedVector2Array([Vector2(0.00000000, 0.68000000), Vector2(0.61000000, 0.61000000), Vector2(0.46000000, 1.00000000)]),
		PackedVector2Array([Vector2(0.00000000, 0.68000000), Vector2(0.46000000, 1.00000000), Vector2(0.00000000, 1.00000000)]),
		PackedVector2Array([Vector2(0.61000000, 0.61000000), Vector2(1.00000000, 0.74000000), Vector2(1.00000000, 1.00000000)]),
		PackedVector2Array([Vector2(0.61000000, 0.61000000), Vector2(1.00000000, 1.00000000), Vector2(0.46000000, 1.00000000)]),
	],
	[
		PackedVector2Array([Vector2(0.01540158, 0.02982847), Vector2(0.49474022, 0.02453877), Vector2(0.39985821, 0.39223276)]),
		PackedVector2Array([Vector2(0.00549612, 0.03336507), Vector2(0.38573660, 0.39787888), Vector2(0.00876728, 0.31535605)]),
		PackedVector2Array([Vector2(0.52960000, 0.02426667), Vector2(0.99020000, 0.02426667), Vector2(0.99020000, 0.27806667)]),
		PackedVector2Array([Vector2(0.52000266, 0.03141637), Vector2(0.97764388, 0.28774946), Vector2(0.41235346, 0.39743416)]),
		PackedVector2Array([Vector2(0.02314812, 0.32339081), Vector2(0.39713735, 0.41212877), Vector2(0.58971453, 0.62108042)]),
		PackedVector2Array([Vector2(0.00720884, 0.33480331), Vector2(0.58729564, 0.61983911), Vector2(0.01549552, 0.69195759)]),
		PackedVector2Array([Vector2(0.42317607, 0.41554343), Vector2(0.98584955, 0.29963535), Vector2(0.99097438, 0.74142122)]),
		PackedVector2Array([Vector2(0.41620000, 0.42026667), Vector2(0.98020000, 0.74926667), Vector2(0.61360000, 0.62706667)]),
		PackedVector2Array([Vector2(0.02231939, 0.69682400), Vector2(0.59646431, 0.63418965), Vector2(0.45121631, 1.00000000)]),
		PackedVector2Array([Vector2(0.01387062, 0.69446739), Vector2(0.43923702, 1.00000000), Vector2(0.00689236, 0.99522889)]),
		PackedVector2Array([Vector2(0.62185139, 0.63749199), Vector2(0.99123939, 0.75563128), Vector2(0.99690922, 1.00000000)]),
		PackedVector2Array([Vector2(0.61196740, 0.63263381), Vector2(0.98280818, 0.99719948), Vector2(0.47522442, 1.00000000)]),
	],
	[
		PackedVector2Array([Vector2(0.02699481, 0.07106398), Vector2(0.47871646, 0.05672338), Vector2(0.40434303, 0.40525066)]),
		PackedVector2Array([Vector2(0.00871674, 0.05611753), Vector2(0.37482101, 0.39620082), Vector2(0.01758706, 0.32204718)]),
		PackedVector2Array([Vector2(0.54702222, 0.05930770), Vector2(0.98148889, 0.05930770), Vector2(0.98148889, 0.29870770)]),
		PackedVector2Array([Vector2(0.53089016, 0.07231130), Vector2(0.95725863, 0.31853891), Vector2(0.42185121, 0.41647290)]),
		PackedVector2Array([Vector2(0.04847511, 0.32845884), Vector2(0.39744582, 0.41942195), Vector2(0.57044250, 0.62018722)]),
		PackedVector2Array([Vector2(0.00701069, 0.36007540), Vector2(0.56563236, 0.61749883), Vector2(0.02947621, 0.69665232)]),
		PackedVector2Array([Vector2(0.44316028, 0.45343982), Vector2(0.97147144, 0.33863009), Vector2(0.98536828, 0.75525320)]),
		PackedVector2Array([Vector2(0.43133819, 0.45388141), Vector2(0.96333819, 0.76421474), Vector2(0.61753819, 0.64894808)]),
		PackedVector2Array([Vector2(0.04296984, 0.70987267), Vector2(0.58576320, 0.65640093), Vector2(0.44126696, 1.00000000)]),
		PackedVector2Array([Vector2(0.03013382, 0.70363215), Vector2(0.41865070, 1.00000000), Vector2(0.01121548, 0.98706534)]),
		PackedVector2Array([Vector2(0.62884675, 0.66553213), Vector2(0.98196653, 0.76971053), Vector2(0.99733768, 1.00000000)]),
		PackedVector2Array([Vector2(0.61139782, 0.65218199), Vector2(0.96863777, 0.99240591), Vector2(0.48996441, 1.00000000)]),
	],
	[
		PackedVector2Array([Vector2(0.04010903, 0.11264002), Vector2(0.46388222, 0.09038559), Vector2(0.40826070, 0.41924742)]),
		PackedVector2Array([Vector2(0.01173991, 0.08709764), Vector2(0.36273579, 0.40312949), Vector2(0.02551159, 0.33691716)]),
		PackedVector2Array([Vector2(0.56444444, 0.11760849), Vector2(0.97277778, 0.11760849), Vector2(0.97277778, 0.34260849)]),
		PackedVector2Array([Vector2(0.54128655, 0.13664189), Vector2(0.93693058, 0.37217804), Vector2(0.43178287, 0.45900555)]),
		PackedVector2Array([Vector2(0.07212656, 0.34606978), Vector2(0.39624064, 0.43830774), Vector2(0.55055160, 0.63027544)]),
		PackedVector2Array([Vector2(0.00902211, 0.39560937), Vector2(0.54432902, 0.62657896), Vector2(0.04388519, 0.71136194)]),
		PackedVector2Array([Vector2(0.46717508, 0.49796142), Vector2(0.96130545, 0.38493331), Vector2(0.98288109, 0.77631723)]),
		PackedVector2Array([Vector2(0.44704784, 0.48622053), Vector2(0.94704784, 0.77788720), Vector2(0.62204784, 0.66955386)]),
		PackedVector2Array([Vector2(0.06348448, 0.72348228), Vector2(0.57466424, 0.67850970), Vector2(0.43185128, 1.00000000)]),
		PackedVector2Array([Vector2(0.04549666, 0.71403048), Vector2(0.39836507, 1.00000000), Vector2(0.01613827, 0.97992738)]),
		PackedVector2Array([Vector2(0.63347587, 0.69295624), Vector2(0.96946457, 0.78395877), Vector2(0.99331826, 1.00000000)]),
		PackedVector2Array([Vector2(0.61072520, 0.67195955), Vector2(0.95339376, 0.98820973), Vector2(0.50371863, 1.00000000)]),
	],
	[
		PackedVector2Array([Vector2(0.05592193, 0.16718484), Vector2(0.45148918, 0.13815872), Vector2(0.41283878, 0.44691186)]),
		PackedVector2Array([Vector2(0.01418662, 0.13075225), Vector2(0.34911534, 0.42312630), Vector2(0.03216110, 0.36442367)]),
		PackedVector2Array([Vector2(0.58186667, 0.21800017), Vector2(0.96406667, 0.21800017), Vector2(0.96406667, 0.42860017)]),
		PackedVector2Array([Vector2(0.54994101, 0.21803156), Vector2(0.91542730, 0.44229937), Vector2(0.44089466, 0.51866974)]),
		PackedVector2Array([Vector2(0.09820939, 0.37665638), Vector2(0.39768866, 0.46922795), Vector2(0.53424374, 0.65181674)]),
		PackedVector2Array([Vector2(0.00442261, 0.43372496), Vector2(0.51464717, 0.63945028), Vector2(0.04989402, 0.72846134)]),
		PackedVector2Array([Vector2(0.50061203, 0.54197226), Vector2(0.96076508, 0.43140549), Vector2(0.98892510, 0.79749072)]),
		PackedVector2Array([Vector2(0.46116871, 0.51896365), Vector2(0.92916871, 0.79196365), Vector2(0.62496871, 0.69056365)]),
		PackedVector2Array([Vector2(0.08385022, 0.73764186), Vector2(0.56317616, 0.70050170), Vector2(0.42297362, 1.00000000)]),
		PackedVector2Array([Vector2(0.06472684, 0.72562051), Vector2(0.38322127, 1.00000000), Vector2(0.02643512, 0.97381957)]),
		PackedVector2Array([Vector2(0.63690315, 0.71970384), Vector2(0.95495176, 0.79833826), Vector2(0.98606379, 1.00000000)]),
		PackedVector2Array([Vector2(0.60588229, 0.69195260), Vector2(0.93302197, 0.98461162), Vector2(0.51241341, 1.00000000)]),
	],
]


static func source() -> Array:
	return _poses[0]


static func pose(level: int) -> Array:
	return _poses[clampi(level, 0, 4)]
