"""Current U13 castle pressure playtest values, mirrored by native rules."""

MAX_INTEGRITY = 17
WRIGHT_PAIR_BUILD = 5
WRIGHT_PAIR_REPAIR = 3
PENITENT_PAIR_SCREEN = 3
BUTCHER_PAIR_KILLS = 2
FORGE_REPAIR = 1
RAPID_CONSTRUCTION_REPAIR = 2
